FROM maven:3.6.3-jdk-8-slim

COPY ./ ./

# ENV SONARQUBE_SCANNER_PARAMS '{ "sonar.branch.name" : "master-docker", "sonar.organization" : "ron190-github", "sonar.host.url" : "https://sonarcloud.io", "sonar.login" : "" }'
# ENV SONAR_TOKEN ${SONAR_TOKEN}

# Ignore repositories errors
RUN apt-get update -y || true

# Install VNC support, shell and network tools
RUN apt-get install tightvncserver xfonts-base dos2unix iproute2 net-tools iputils-ping -y

RUN dos2unix /model/src/test/resources/vnc/execute-on-vnc.sh

# Define user for VNC
ENV USER vnc-user-jsql

# Disable Oracle tests
ENV FROM_TRAVIS true

CMD ["/bin/bash"]