FROM ubuntu:18.04
ENV MYSQL_ROOT_PASSWORD password
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y php php-mysql libapache2-mod-php mysql-server
RUN echo "[mysqld]" > /etc/my.cnf
RUN echo "port=3308" >> /etc/my.cnf
RUN echo "secure_file_priv=''" >> /etc/my.cnf
#RUN echo "Listen 8079" >> /etc/apache2/ports.conf
EXPOSE 80 3308 8079
COPY ./lamp/start-script.sh /root/
COPY ./lamp/php/get.php /var/www/html/
COPY ./lamp/php/get2.php /var/www/html/
COPY ./lamp/php/phpinfo.php /var/www/html/
RUN chmod +x /root/start-script.sh
ENTRYPOINT ["/root/start-script.sh"]