ARG JSQL_DOCKERFILE=${JSQL_DOCKERFILE}
ARG MAVEN_NASHORN=${MAVEN_NASHORN}
FROM maven:${JSQL_DOCKERFILE}

COPY ./ ./

ENV MAVEN_NASHORN ${MAVEN_NASHORN}

# Disable Oracle tests
ENV FROM_CI_PIPELINE true

# Define user for VNC
ENV USER vnc-user-jsql

# Ignore repositories errors
RUN apt-get update -y || true

# Install VNC support, shell and network tools
RUN apt-get install tightvncserver xfonts-base dos2unix iproute2 net-tools iputils-ping -y

RUN dos2unix /model/src/test/resources/vnc/execute-on-vnc.sh

CMD ["/bin/bash"]